### ISSUE TITLE
Role assumes services live in /usr/lib/systemd

### ISSUE THREAD

**Issue by morgangraphics** [zaxos/tomcat-ansible-role#6]
This one is not necessarily anything you did wrong but Ubuntu 14.04 uses upstart instead of ststemd.  While, I wouldn't expect you to support a OS that is 10+ years old at this point this issue is more for posterity should someone else run into the `"msg": "Destination directory /usr/lib/systemd/system does not exist"` error I ran into. I had to wrap the existing functionality in a block

```
- block:

    - name: Configure service file {{ tomcat_service_name }}.service
      template:
        src: tomcat.service.j2
        dest: /usr/lib/systemd/system/{{ tomcat_service_name }}.service
      notify: restart tomcat

    - name: Enable tomcat service on startup
      systemd:
        name: "{{ tomcat_service_name }}"
        enabled: "{% if tomcat_service_enabled_on_startup %}yes{% else %}no{% endif %}"
        daemon_reload: yes

  when: ansible_facts['distribution'] != "Ubuntu" and ansible_facts['distribution_version'] != '14.04'
```

**Comment by mstargard** [comment]
On RedHat 7, /usr/lib/systemd/system is where the unit files for the system packages live. You should put the unit file in /etc/systemd/system, or make it a variable that you can override.

**Comment by morgangraphics** [comment]
I've run into other issues where the init system has changed a few times between Ubuntu systems and adding a `when` check that ties a test to a specific OS and OS version is not scalable. I have a more generic test that will give you the init system as a result

The downside is that you need to know what the init system you are targeting.

```yaml
- name: test init system
    shell: |
      set -e pipefail
      ps -p1 | grep "init\|upstart\|systemd" | awk '{print $4}'
    register: init_system
    changed_when: init_system.stdout != 0
```


```
- name: "Handle init related services - Ubuntu 14.04"
    block:

      - name: "Create TAAS - Tomcat As A Service"
        template:
          src: tomcat.init.service.conf.j2
          dest: "/etc/init/tomcat.conf"
        become: yes

      - name: Reload initctl Configuration
        command: initctl reload-configuration
        become: true

    when: init_system.stdout == 'init'
```


and/or 


```
- name: "Handle systemd related services - Ubuntu 18.04"
    block:

      - name: "Create TAAS - Tomcat As A Service"
        template:
          src: tomcat.systemd.service.j2
          dest: "/etc/systemd/system/tomcat.service"
        become: yes

      - name: Reload systemctl Configuration
        command: systemctl daemon-reload
        become: true

    when: init_system.stdout == 'systemd'
```

The check could be expanded to check for init systems on other OS's
